version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"

  - package-ecosystem: "gradle"
    directories:
      - "/packages/react-native-nitro-modules/android/"
      - "/packages/react-native-nitro-image/android/"
      - "/example/android/"
    schedule:
      interval: "daily"
    labels:
      - "nitro-core"
      - "dependencies"
      - "kotlin"

  - package-ecosystem: "npm"
    directories:
      - "/docs/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    groups:
      docusaurus:
        patterns:
          - "@docusaurus/*"

  - package-ecosystem: "npm"
    directories:
      - "/packages/react-native-nitro-modules/"
      - "/packages/react-native-nitro-image/"
      - "/example/"
    schedule:
      interval: "daily"
    labels:
      - "nitro-core"
      - "dependencies"
      - "typescript"
    groups:
      rncli:
        patterns:
          - "@react-native-community/cli*"
      babel:
        patterns:
          - "@babel/*"
      rn:
        patterns:
          - "@react-native/*"

  - package-ecosystem: "npm"
    directories:
      - "/packages/nitrogen/"
    schedule:
      interval: "daily"
    labels:
      - "nitrogen"
      - "dependencies"
      - "typescript"
